fix: adjust subprocess node in case workflow doesnt exist
flow-build/engine pull request #251
Opened 2023-03-08 14:48 UTC by pedropereiraassis

**What type of PR is this?**
bug

**What this PR does / why we need it:**

When a SubProcess Node try to create a process for a workflow_name that doesn't exist the engine goes into a continue process of ROLLBACK ON EXEC and the parent_process keeps in state DELEGATED.

This PR adjusts that by setting the state of the process as ERROR when the workflow_name doesn't exist (along with some refactoring)

**Which issue(s) this PR fixes:**

Fixes #

2023-03-08 21:54 UTC, gustavo-fdte requested changes

2023-03-08 21:54 UTC, gustavo-fdte commented on src/core/workflow/nodes/subProcess.js
> +
Para manter o mesmo padrão, seria importante colocar o evento aqui,
```
          emitter.emit("PROCESS.SUBPROCESS.NEW", `NEW SUBPROCESS ON PID [${p_lock.id}] SPID [${child_process.id}]`, {
            process_id: p_lock.id,
            sub_process_id: child_process.id,
          });
```

2023-03-08 21:54 UTC, gustavo-fdte commented on src/core/workflow/nodes/subProcess.js
> +          initial_bag
faltou injetar o execution_data na initial_bag.
Vc precisa passar para o subProcesso os dados que estão no input do parameters da spec além de injetar na bag o parent_process_data.

Aproveita aqui para reescrever o actor_data, incluindo/substituindo no actor_data recebido o atributo parentProcessData.id.
Dá uma olhada de como está feito no StartProcessNode para ficar ambos iguais.

2023-03-09 13:34 UTC, gustavo-fdte approved these changes

2023-03-10 21:01 UTC, imagure approved these changes

2023-03-11 13:43 UTC, merged