feat: adds 'events' on node specs and setter to listen to EventNode n…
flow-build/engine pull request #278
Opened 2023-04-20 17:53 UTC by imagure

…otifications

**What type of PR is this?**
feature

**What this PR does / why we need it**:
Extends event nodes feature to add new node type (type: event)

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., usage docs, etc.**:

```docs
```

2023-04-20 22:30 UTC, gustavo-fdte requested changes

2023-04-20 22:30 UTC, gustavo-fdte commented on src/core/workflow/nodes/event.js
> +            input: { type: "object" },
não faltou a key? 
https://fastchannel.atlassian.net/browse/ADM-104

2023-04-20 22:30 UTC, gustavo-fdte commented on src/core/workflow/nodes/event.js
> +  async run({ bag = {}, input = {}, external_input = null, actor_data = {}, environment = {}, parameters = {} }, lisp) {
porque precisou implementar um run específico para ele, não seria o caso de implementar somente o _run?

2023-04-20 22:30 UTC, gustavo-fdte commented on src/core/workflow/nodes/event.js
> +        return [execution_data, ProcessStatus.WAITING];
vc vê algum problema em usarmos o status PENDING ao invés de WAITING?

2023-04-20 22:30 UTC, gustavo-fdte commented on src/core/utils/node_factory.js
> +  signal: nodes.EventNode
Dessa forma vc não está permitindo que eu gere uma systemTask da categoria signal?
O correto seria que o eventNode fosse evocado somente via type: event.

2023-04-20 22:33 UTC, gustavo-fdte requested changes

2023-04-20 22:33 UTC, gustavo-fdte commented on src/core/workflow/nodes/start.js
> -            events: {
um startNode pode ser um signalStartNode, mas tbm pode ser um timerStartNode ou uma messageStartNode, sendo que o timer tbm é um evento... Nesse caso vc não está criando uma spec que só atende a signal?

2023-04-24 12:40 UTC, imagure commented on src/core/workflow/nodes/event.js
> +  async run({ bag = {}, input = {}, external_input = null, actor_data = {}, environment = {}, parameters = {} }, lisp) {
Esse node precisava de uma lógica semelhante ao da UserTask, mas não queria herdar dela para isso.
Então coloquei o "run" para conseguir tratar o retorno de status de acordo com o "external_input"

2023-04-24 12:41 UTC, imagure commented on src/core/workflow/nodes/event.js
> +  async run({ bag = {}, input = {}, external_input = null, actor_data = {}, environment = {}, parameters = {} }, lisp) {
A alternativa seria alterar o "run" do Node base.
Aí preferi não mexer (pelo menos num primeiro momento). 
Mas vou testar mudar lá tbm.

2023-04-24 20:45 UTC, gustavo-fdte approved these changes

2023-04-25 17:39 UTC, merged