Feature/flow 71 environment variables table
flow-build/engine pull request #291
Opened 2023-05-17 17:10 UTC by pedropereiraassis

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
/kind feature

**What this PR does / why we need it**:
Adds new entity EnvironmentVariable in order to save environment variables of blueprints inside a table

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., usage docs, etc.**:

```docs
```

2023-05-17 18:17 UTC, gustavo-fdte requested changes

2023-05-17 18:17 UTC, gustavo-fdte commented on src/cockpit/tests/unitary/cockpit.test.js
> +  test("fetchEnvironmentVariable should work", async () => {
não seria o caso de incluir um teste para verificar se vc está seguindo a hierarquia correta de resolução das variáveis "de ambiente"?
A tabela de variáveis não substitui variáveis de ambiente, mas estende elas.
O fetchAll não funcionar ok, pois vc não vai buscar as ENVs de ambiente, mas o fetch por key tem como resolver e verificar a variável no ambiente e na tabela.

2023-05-17 18:17 UTC, gustavo-fdte commented on src/core/workflow/workflow.js
> +    const environment_variables = await EnvironmentVariable.fetchAll();
pessoalmente não gostei da solução... vc vai no banco e retorna 100% da tabela e joga na memória da aplicação, me parece uma solução bem pouco performática.
Faria mais sentido pegar a spec, fazer um Object.keys( spec.environment ) e chamar um método de fetchMany.

Outro ponto é que eu acho que esse fetch é responsabilidade daquela função `validate_environment_variables` e não do createProcess.

* o nome da função está errado. Validate algo gera a expectativa de uma resposta boleana (válido/inválido)... a função deveria chamar `resolve_environment_variables`.

2023-05-18 13:20 UTC, imagure approved these changes

2023-05-19 11:34 UTC, gustavo-fdte commented on src/core/workflow/workflow.js
> +    const parsedBlueprint = await Blueprint.parseSpec(this._blueprint_spec);
Ficou beeeeem melhor assim.

2023-05-19 12:50 UTC, pedropereiraassis commented on src/core/workflow/blueprint.js
> +        const error_message = `Environment variable ${key} not found in ambient`;
Mensagem alterada

2023-05-23 13:22 UTC, imagure approved these changes

2023-05-25 17:36 UTC, gustavo-fdte approved these changes

2023-05-25 18:03 UTC, merged